import test from "node:test";
import assert from "node:assert/strict";
import { createFighter, learnTechnique, useTechnique, recordTechniqueExperience, getTechniqueProgress } from "../src/index.mjs";
import { PROGRESSION_ENGINE_VERSION, evaluateTechniqueProgress } from "../src/progression-engine.mjs";

const technique = (id = "jab") => ({ id, name: id === "jab" ? "Jab" : "Bandal Tchagui", art: id === "jab" ? "boxing" : "taekwondo", family: id === "jab" ? "punches" : "kicks" });
const empty = () => ({ observed: 0, recognized: 0, defended: 0, reproduced: 0, adapted: 0, mastered: 0 });

test("a fighter can learn a named technique at zero proficiency", () => { let fighter = learnTechnique(createFighter({ id: "p1", name: "Rookie" }), technique("bandal-tchagui")); assert.deepEqual(getTechniqueProgress(fighter, "bandal-tchagui"), { ...technique("bandal-tchagui"), level: 1, xp: 0, uses: 0, experience: empty(), evidence: [] }); });
test("using a learned technique produces technique-specific XP and usage history", () => { let fighter = learnTechnique(createFighter({ id: "p1", name: "Rookie" }), technique("bandal-tchagui")); fighter = useTechnique(fighter, "bandal-tchagui", { repetitions: 10 }); const p = getTechniqueProgress(fighter, "bandal-tchagui"); assert.equal(p.uses, 10); assert.ok(p.xp > 0); assert.equal(fighter.history.at(-1).type, "technique-use"); });
test("contextual martial experience is recorded independently from raw repetitions", () => { let fighter = learnTechnique(createFighter({ id: "p1", name: "Rookie" }), technique("bandal-tchagui")); fighter = recordTechniqueExperience(fighter, "bandal-tchagui", { kind: "defended", quality: 0.8 }); const p = getTechniqueProgress(fighter, "bandal-tchagui"); assert.equal(p.uses, 0); assert.equal(p.experience.defended, 1); assert.equal(p.evidence.length, 1); assert.ok(p.xp > 0); });
test("progression engine is versioned and deterministic", () => { assert.equal(PROGRESSION_ENGINE_VERSION, 1); const sample = { ...technique(), uses: 12, experience: { ...empty(), observed: 2, recognized: 1, defended: 1, reproduced: 1 }, evidence: [{ kind: "observed", quality: 1 }, { kind: "defended", quality: 0.75 }] }; assert.deepEqual(evaluateTechniqueProgress(sample), evaluateTechniqueProgress(structuredClone(sample))); });
test("higher-order adaptation is worth more than passive observation", () => { const base = { ...technique(), uses: 0, experience: empty() }; const observed = evaluateTechniqueProgress({ ...base, experience: { ...empty(), observed: 1 }, evidence: [{ kind: "observed", quality: 1 }] }); const adapted = evaluateTechniqueProgress({ ...base, experience: { ...empty(), adapted: 1 }, evidence: [{ kind: "adapted", quality: 1 }] }); assert.ok(adapted.xp > observed.xp); });
test("quality changes learning value without changing the number of experiences", () => { const base = { ...technique(), uses: 0, experience: { ...empty(), reproduced: 1 } }; assert.ok(evaluateTechniqueProgress({ ...base, evidence: [{ kind: "reproduced", quality: 1 }] }).xp > evaluateTechniqueProgress({ ...base, evidence: [{ kind: "reproduced", quality: 0.25 }] }).xp); });
test("engine rejects invalid numeric evidence instead of producing NaN or Infinity", () => { const base = { ...technique(), uses: 1, experience: { ...empty(), observed: 1 } }; assert.throws(() => evaluateTechniqueProgress({ ...base, evidence: [{ kind: "observed", quality: NaN }] }), /quality/); assert.throws(() => evaluateTechniqueProgress({ ...base, evidence: [{ kind: "observed", quality: Infinity }] }), /quality/); });

test("massive raw repetitions alone cannot produce mastery", () => { const result = evaluateTechniqueProgress({ ...technique(), uses: 100000, experience: empty(), evidence: [] }); assert.ok(result.level > 1); assert.notEqual(result.proficiency.stage, "mastered"); assert.equal(result.proficiency.diversity, 0); });
test("diverse contextual evidence advances proficiency", () => { const experience = { observed: 1, recognized: 1, defended: 1, reproduced: 1, adapted: 1, mastered: 0 }; const evidence = Object.keys(experience).filter(k => experience[k]).map(kind => ({ kind, quality: 1 })); const result = evaluateTechniqueProgress({ ...technique(), uses: 200, experience, evidence }); assert.ok(result.proficiency.diversity >= 5); assert.ok(["adapted", "mastered"].includes(result.proficiency.stage)); });
test("one high-order event cannot fabricate missing lower evidence categories", () => { const experience = { ...empty(), mastered: 1 }; const result = evaluateTechniqueProgress({ ...technique(), uses: 5000, experience, evidence: [{ kind: "mastered", quality: 1 }] }); assert.equal(result.proficiency.diversity, 1); assert.notEqual(result.proficiency.stage, "mastered"); });

test("training one technique does not grant free proficiency to another", () => { let fighter = createFighter({ id: "p1", name: "Rookie" }); fighter = learnTechnique(fighter, technique("bandal-tchagui")); fighter = learnTechnique(fighter, technique()); fighter = useTechnique(fighter, "bandal-tchagui", { repetitions: 20 }); assert.equal(getTechniqueProgress(fighter, "jab").xp, 0); });
test("technique level is earned from technique XP rather than global level-up points", () => { let fighter = learnTechnique(createFighter({ id: "p1", name: "Rookie" }), technique("bandal-tchagui")); fighter = useTechnique(fighter, "bandal-tchagui", { repetitions: 120 }); assert.ok(getTechniqueProgress(fighter, "bandal-tchagui").level > 1); assert.equal(fighter.progression.level, 1); });
test("repeated bulk practice has diminishing XP return", () => { let fighter = learnTechnique(createFighter({ id: "p1", name: "Rookie" }), technique("bandal-tchagui")); fighter = useTechnique(fighter, "bandal-tchagui", { repetitions: 10 }); const first = getTechniqueProgress(fighter, "bandal-tchagui").xp; fighter = useTechnique(fighter, "bandal-tchagui", { repetitions: 100 }); const total = getTechniqueProgress(fighter, "bandal-tchagui").xp; assert.ok((total - first) / 100 < first / 10); });
test("invalid experience kinds and qualities are rejected", () => { let fighter = learnTechnique(createFighter({ id: "p1", name: "Rookie" }), technique()); assert.throws(() => recordTechniqueExperience(fighter, "jab", { kind: "magic", quality: 1 }), /invalid experience kind/); assert.throws(() => recordTechniqueExperience(fighter, "jab", { kind: "observed", quality: 2 }), /quality/); });
test("an unknown technique cannot be progressed by use", () => { assert.throws(() => useTechnique(createFighter({ id: "p1", name: "Rookie" }), "flying-magic-kick", { repetitions: 1 }), /technique not learned/); });
