import { EXPERIENCE_KINDS, evaluateTechniqueProgress } from "./progression-engine.mjs";
const VERSION = 1;
const clamp=(v,min,max)=>Math.min(max,Math.max(min,v)); const bounded=v=>clamp(Number(v),0,100); const round2=v=>Math.round(v*100)/100; const finite=v=>Number.isFinite(v); const inRange=(v,min,max)=>finite(v)&&v>=min&&v<=max;
const emptyExperience=()=>Object.fromEntries(EXPERIENCE_KINDS.map(k=>[k,0]));
const validExperience=e=>e&&EXPERIENCE_KINDS.every(k=>Number.isInteger(e[k])&&e[k]>=0); const validEvidence=e=>Array.isArray(e)&&e.every(x=>x&&EXPERIENCE_KINDS.includes(x.kind)&&inRange(x.quality,0,1));
const validLegacyProgress=p=>p===undefined||(p&&finite(p.xp)&&p.xp>=0&&Number.isInteger(p.level)&&p.level>=1);
const validTechnique=t=>t&&typeof t.id==="string"&&t.id&&typeof t.name==="string"&&t.name&&typeof t.art==="string"&&t.art&&typeof t.family==="string"&&t.family&&Number.isInteger(t.level)&&t.level>=1&&finite(t.xp)&&t.xp>=0&&Number.isInteger(t.uses)&&t.uses>=0&&validExperience(t.experience)&&validEvidence(t.evidence)&&validLegacyProgress(t.legacyProgress);
const refreshTechnique=t=>{const d=evaluateTechniqueProgress(t);t.xp=d.xp;t.level=d.level;return d;};
const migrateTechnique=t=>{if(!t||typeof t!=="object")return t; const n=structuredClone(t); if(!n.experience&&!n.evidence){n.legacyProgress={xp:n.xp,level:n.level};n.experience=emptyExperience();n.evidence=[];refreshTechnique(n);} else {if(!n.experience)n.experience=emptyExperience();if(!n.evidence)n.evidence=[];} return n;};
const migrateFighter=f=>{if(!f||f.schemaVersion!==VERSION)return f; const n=structuredClone(f); if(n.martial?.techniques) for(const [id,t] of Object.entries(n.martial.techniques)) n.martial.techniques[id]=migrateTechnique(t); return n;};
export function validateFighter(f){const ok=f&&f.schemaVersion===VERSION&&typeof f.id==="string"&&f.id&&typeof f.name==="string"&&f.name&&f.body&&f.needs&&f.condition&&f.martial&&f.martial.techniques&&Array.isArray(f.history)&&finite(f.condition.staminaMax)&&f.condition.staminaMax>0&&inRange(f.condition.stamina,0,f.condition.staminaMax)&&inRange(f.condition.combatStamina,0,f.condition.staminaMax)&&inRange(f.condition.fatigue,0,100)&&inRange(f.condition.health,0,100)&&inRange(f.condition.pain,0,100)&&[f.needs.nutrition,f.needs.hydration,f.needs.sleep].every(v=>inRange(v,0,100))&&Array.isArray(f.condition.injuries)&&f.condition.injuries.every(i=>i&&typeof i.id==="string"&&i.id&&typeof i.region==="string"&&i.region&&inRange(i.severity,0,100)&&inRange(i.pain,0,100))&&Object.values(f.martial.techniques).every(validTechnique);if(!ok)throw new Error("invalid fighter state");return true;}
export function createFighter({id,name,background="untrained",body={}}){if(!id||!name)throw new Error("fighter requires id and name");const staminaMax=Math.max(1,Number(body.staminaMax??100));const f={schemaVersion:VERSION,id,name,background,progression:{level:1,experience:0},body:{massKg:Number(body.massKg??70),muscleMass:Number(body.muscleMass??10),strength:Number(body.strength??10),endurance:Number(body.endurance??10),mobility:Number(body.mobility??10),flexibility:Number(body.flexibility??10),balance:Number(body.balance??10),coordination:Number(body.coordination??10)},needs:{nutrition:100,hydration:100,sleep:100},condition:{staminaMax,stamina:staminaMax,combatStamina:staminaMax,fatigue:0,health:100,pain:0,injuries:[]},martial:{arts:{},techniques:{},integrations:{}},history:[]};validateFighter(f);return f;}
export function learnTechnique(f,t){validateFighter(f);if(!t?.id||!t?.name||!t?.art||!t?.family)throw new Error("technique requires id, name, art and family");if(f.martial.techniques[t.id])throw new Error("technique already learned");const n=structuredClone(f);n.martial.techniques[t.id]={id:t.id,name:t.name,art:t.art,family:t.family,level:1,xp:0,uses:0,experience:emptyExperience(),evidence:[]};n.history.push({type:"technique-learned",techniqueId:t.id});validateFighter(n);return n;}
export function getTechniqueProgress(f,id){validateFighter(f);const t=f.martial.techniques[id];if(!t)throw new Error("technique not learned");return structuredClone(t);}
export function recordTechniqueExperience(f,id,{kind,quality=1,source,contextId,timestamp}={}){validateFighter(f);if(!f.martial.techniques[id])throw new Error("technique not learned");if(!EXPERIENCE_KINDS.includes(kind))throw new Error("invalid experience kind");const q=Number(quality);if(!finite(q)||q<0||q>1)throw new Error("quality must be between 0 and 1");const n=structuredClone(f),t=n.martial.techniques[id];t.experience[kind]++;const e={kind,quality:q};if(source!==undefined)e.source=source;if(contextId!==undefined)e.contextId=contextId;if(timestamp!==undefined)e.timestamp=timestamp;t.evidence.push(e);const before=t.xp,d=refreshTechnique(t);n.history.push({type:"technique-experience",techniqueId:id,...e,xpGain:round2(d.xp-before),engineVersion:d.engineVersion});validateFighter(n);return n;}
export function useTechnique(f,id,{repetitions=1}={}){validateFighter(f);if(!f.martial.techniques[id])throw new Error("technique not learned");const reps=Math.floor(Number(repetitions));if(!finite(reps)||reps<=0)throw new Error("repetitions must be positive");const n=structuredClone(f),t=n.martial.techniques[id],before=t.xp;t.uses+=reps;const d=refreshTechnique(t);n.history.push({type:"technique-use",techniqueId:id,repetitions:reps,xpGain:round2(d.xp-before),totalUses:t.uses,level:t.level,engineVersion:d.engineVersion});validateFighter(n);return n;}
export function applyNeeds(f,c={}){validateFighter(f);const n=structuredClone(f);for(const k of ["nutrition","hydration","sleep"])n.needs[k]=bounded(n.needs[k]+Number(c[k]??0));n.history.push({type:"needs",changes:{nutrition:Number(c.nutrition??0),hydration:Number(c.hydration??0),sleep:Number(c.sleep??0)}});validateFighter(n);return n;}
export function addInjury(f,i){validateFighter(f);if(!i?.id||!i?.region)throw new Error("injury requires id and region");const n=structuredClone(f),x={id:i.id,region:i.region,severity:bounded(i.severity??0),pain:bounded(i.pain??0)};n.condition.injuries.push(x);n.condition.pain=bounded(n.condition.injuries.reduce((a,z)=>a+z.pain,0));n.history.push({type:"injury",...x});validateFighter(n);return n;}
export function recoverInjuries(f,{severity=0,pain=0}={}){validateFighter(f);const n=structuredClone(f),s=Math.max(0,Number(severity)),p=Math.max(0,Number(pain));n.condition.injuries=n.condition.injuries.map(i=>({...i,severity:bounded(i.severity-s),pain:bounded(i.pain-p)})).filter(i=>i.severity>0||i.pain>0);n.condition.pain=bounded(n.condition.injuries.reduce((a,i)=>a+i.pain,0));n.history.push({type:"injury-recovery",severity:s,pain:p});validateFighter(n);return n;}
export function applyActivity(f,a){validateFighter(f);const n=structuredClone(f),s=Math.max(0,Number(a.staminaCost??0)),g=Math.max(0,Number(a.fatigueGain??s*.25));if(n.condition.stamina<s)throw new Error("insufficient stamina");n.condition.stamina=clamp(n.condition.stamina-s,0,n.condition.staminaMax);n.condition.fatigue=bounded(n.condition.fatigue+g);n.history.push({type:"activity",id:a.id??"unknown",staminaCost:s,fatigueGain:g});validateFighter(n);return n;}
export function recover(f,{stamina=0,fatigue=0}={}){validateFighter(f);const n=structuredClone(f);n.condition.stamina=clamp(n.condition.stamina+Math.max(0,stamina),0,n.condition.staminaMax);n.condition.fatigue=bounded(n.condition.fatigue-Math.max(0,fatigue));n.history.push({type:"recovery",stamina:Math.max(0,stamina),fatigue:Math.max(0,fatigue)});validateFighter(n);return n;}
export function getReadiness(f){validateFighter(f);const s=bounded(f.condition.stamina/f.condition.staminaMax*100),needs=(f.needs.nutrition+f.needs.hydration+f.needs.sleep)/3;return round2(bounded(s*.4+needs*.25+(100-f.condition.fatigue)*.25+(100-f.condition.pain)*.1));}
export function prepareCombat(f){validateFighter(f);const n=structuredClone(f),r=getReadiness(n)/100;n.condition.combatStamina=round2(clamp(n.condition.stamina*r,0,n.condition.stamina));n.history.push({type:"combat-preparation",readiness:round2(r*100),combatStamina:n.condition.combatStamina});validateFighter(n);return n;}
export function serializeFighter(f){validateFighter(f);return JSON.stringify(f);}
export function deserializeFighter(s){let f=JSON.parse(s);if(f.schemaVersion!==VERSION)throw new Error("unsupported fighter schema version");f=migrateFighter(f);validateFighter(f);return f;}
