import Phaser from "phaser";
const W=960,H=540;
const roster=[{id:"norman",name:'Norman "The Psychic" Albert',color:0xa445db},{id:"khabib",name:"Khabib Nurgaliyev",color:0x38b89d}];
function title(scene,text,y=90,size=38){return scene.add.text(W/2,y,text,{fontFamily:"Arial",fontSize:size,color:"#fff",fontStyle:"bold"}).setOrigin(.5)}
export class BootScene extends Phaser.Scene{constructor(){super("Boot")}create(){this.scene.start("Menu")}}
export class MenuScene extends Phaser.Scene{constructor(){super("Menu")}create(){title(this,"KILLER FISTS: ORANKORK");title(this,"ENTER — JOGAR",280,25);this.input.keyboard.once("keydown-ENTER",()=>this.scene.start("Select"))}}
export class CharacterSelectScene extends Phaser.Scene{constructor(){super("Select")}create(){title(this,"SELEÇÃO DE LUTADORES");roster.forEach((r,i)=>title(this,(i+1)+". "+r.name,210+i*60,24));title(this,"ENTER — NORMAN VS KHABIB",430,19);this.input.keyboard.once("keydown-ENTER",()=>this.scene.start("Fight"))}}
export class FightScene extends Phaser.Scene{
constructor(){super("Fight")}
create(){this.keys=this.input.keyboard.addKeys("A,D,W,S,F,G,UP,DOWN,LEFT,RIGHT,K,L,R,ESC");this.fighters=[this.makeFighter(260,roster[0]),this.makeFighter(700,roster[1])];this.rounds=[0,0];this.round=1;this.resetRound();this.input.keyboard.on("keydown-ESC",()=>this.scene.start("Select"));this.input.keyboard.on("keydown-R",()=>this.scene.restart());}
makeFighter(x,r){const body=this.add.rectangle(x,410,58,118,r.color);return {x,y:410,vy:0,hp:100,body,face:1,cool:0,stun:0,id:r.id}}
resetRound(){this.ended=false;this.clock=99;this.fighters.forEach((f,i)=>{f.x=i?700:260;f.y=410;f.vy=0;f.hp=100;f.cool=0;f.stun=0;f.body.setPosition(f.x,f.y)});this.status?.destroy();this.drawHud()}
drawHud(){this.hud?.destroy();this.hud=this.add.text(22,18,"",{fontFamily:"Arial",fontSize:21,color:"#fff"});this.updateHud()}
updateHud(){this.hud.setText(`NORMAN: ${this.fighters[0].hp} HP   ${this.rounds[0]}  |  ${Math.ceil(this.clock)}s  |  ${this.rounds[1]}   KHABIB: ${this.fighters[1].hp} HP\nA/D W S F G   vs   ←/→ ↑ ↓ K L     R: reiniciar   ESC: seleção`)}
strike(a,b,damage){if(this.ended||a.cool>0||a.stun>0)return;a.cool=420;if(Math.abs(a.x-b.x)<105&&Math.abs(a.y-b.y)<65){b.hp=Math.max(0,b.hp-damage);b.stun=240;b.x+=Math.sign(b.x-a.x||1)*22;if(b.hp===0)this.finishRound(a)}}
finishRound(winner){if(this.ended)return;this.ended=true;const idx=this.fighters.indexOf(winner);if(idx>=0)this.rounds[idx]++;const match=this.rounds.some(x=>x>=2);this.status=title(this,match?(idx===0?"NORMAN":"KHABIB")+" VENCEU!  R: REINICIAR":idx<0?"EMPATE!":"ROUND PARA "+(idx===0?"NORMAN":"KHABIB"),230,30);if(!match)this.time.delayedCall(1900,()=>{this.round++;this.resetRound()})}
update(_,delta){if(this.ended)return;const dt=Math.min(delta,50);this.clock-=dt/1000;const input=[[this.keys.A,this.keys.D,this.keys.W,this.keys.S,this.keys.F,this.keys.G],[this.keys.LEFT,this.keys.RIGHT,this.keys.UP,this.keys.DOWN,this.keys.K,this.keys.L]];this.fighters.forEach((f,i)=>{const [left,right,up,down,punch,kick]=input[i];f.cool=Math.max(0,f.cool-dt);f.stun=Math.max(0,f.stun-dt);if(f.stun<=0){const direction=(right.isDown?1:0)-(left.isDown?1:0);f.x=Phaser.Math.Clamp(f.x+direction*dt*.28,35,925);if(up.isDown&&f.y>=410)f.vy=-.75;if(Phaser.Input.Keyboard.JustDown(punch))this.strike(f,this.fighters[1-i],8);if(Phaser.Input.Keyboard.JustDown(kick))this.strike(f,this.fighters[1-i],12);f.body.height=down.isDown&&f.y>=410?76:118;}f.vy+=dt*.002;f.y=Math.min(410,f.y+f.vy*dt);if(f.y===410)f.vy=0;f.body.setPosition(f.x,f.y+(118-f.body.height)/2)});if(this.clock<=0){const [a,b]=this.fighters;this.finishRound(a.hp===b.hp?null:a.hp>b.hp?a:b)}this.updateHud()}
}
