import Phaser from "phaser";
const W=960,H=540,FLOOR=444;
const roster=[{id:"kn",name:"KN — Khabib Nurgaliyev",sprite:"kn"},{id:"norman",name:"Norman Albert — Vilão",sprite:"norman"}];
const label=(s,t,x,y,size=24)=>s.add.text(x,y,t,{fontFamily:"Arial",fontSize:size,color:"#f7f7fc",fontStyle:"bold"}).setOrigin(.5);
export class BootScene extends Phaser.Scene{constructor(){super("Boot")}preload(){this.load.svg("kn","/assets/fighters/kn.svg",{width:112,height:176});this.load.svg("norman","/assets/fighters/norman.svg",{width:112,height:176})}create(){this.scene.start("Menu")}}
export class MenuScene extends Phaser.Scene{constructor(){super("Menu")}create(){label(this,"KILLER FISTS: ORANKORK",480,120,43);label(this,"KN — A JORNADA DO LUTADOR",480,205,25);label(this,"ENTER PARA JOGAR",480,350);this.input.keyboard.once("keydown-ENTER",()=>this.scene.start("Select"))}}
export class CharacterSelectScene extends Phaser.Scene{constructor(){super("Select")}create(){label(this,"KN É O PROTAGONISTA",480,95,36);this.add.image(330,295,"kn").setScale(1.4);this.add.image(640,295,"norman").setScale(1.4);label(this,"KN",330,430);label(this,"NORMAN",640,430);label(this,"ENTER — LUTAR",480,492,22);this.input.keyboard.once("keydown-ENTER",()=>this.scene.start("Fight"))}}
export class FightScene extends Phaser.Scene{
constructor(){super("Fight")}
create(){this.cameras.main.setBackgroundColor("#171b30");this.add.rectangle(480,460,960,160,0x343a4c);this.add.rectangle(480,452,960,7,0xb89c6a);this.add.circle(780,120,54,0x7b729d,.22);this.keys=this.input.keyboard.addKeys("A,D,W,S,F,G,UP,DOWN,LEFT,RIGHT,K,L,R,ESC");this.fighters=[this.fighter(265,roster[0],1),this.fighter(695,roster[1],-1)];this.rounds=[0,0];this.round=1;this.aiTimer=0;this.reset();this.input.keyboard.on("keydown-R",()=>this.scene.restart());this.input.keyboard.on("keydown-ESC",()=>this.scene.start("Select"))}
fighter(x,r,face){const sprite=this.add.image(x,FLOOR,r.sprite).setOrigin(.5,1).setScale(1.13);return{x,feet:FLOOR,vy:0,hp:100,stamina:100,cool:0,stun:0,attack:null,face,sprite,name:r.id,grounded:true}}
reset(){this.ended=false;this.timer=99;this.aiTimer=650;this.fighters.forEach((f,i)=>{f.x=i?695:265;f.feet=FLOOR;f.vy=0;f.hp=100;f.stamina=100;f.cool=0;f.stun=0;f.attack=null;f.sprite.setPosition(f.x,f.feet).setAlpha(1).setTint(0xffffff)});this.banner?.destroy();this.hud?.destroy();this.hud=this.add.text(22,15,"",{fontFamily:"Arial",fontSize:19,color:"#ffffff"});this.renderHud()}
renderHud(){const [a,b]=this.fighters;this.healthBars?.[2].setDisplaySize(300*a.hp/100,18);this.healthBars?.[3].setDisplaySize(300*b.hp/100,18);this.hud.setText(`KN  HP ${a.hp}  STA ${Math.floor(a.stamina)}   [${this.rounds[0]}]   ${Math.ceil(this.timer)}s   [${this.rounds[1]}]   NORMAN HP ${b.hp} STA ${Math.floor(b.stamina)}\nKN: A D W S | F/K soco G/L chute     NORMAN: IA adversaria    R reinicia`)}
hit(a,b,kind){if(this.ended||a.stun>0||a.cool>0)return;const kick=kind==="kick",cost=kick?19:11;if(a.stamina<cost)return;a.stamina-=cost;a.cool=kick?440:290;a.attack={until:140,kick};a.sprite.setTint(0xfff2bb);this.time.delayedCall(115,()=>{if(!a.sprite.active)return;a.sprite.clearTint()});const range=kick?123:93;if(Math.abs(a.x-b.x)<=range&&Math.abs(a.feet-b.feet)<100 ){b.hp=Math.max(0,b.hp-(kick?12:8));b.stun=kick?300:190;b.x=Phaser.Math.Clamp(b.x+a.face*(kick?33:19),55,905);b.sprite.setTint(0xff6464);this.time.delayedCall(160,()=>{if(b.sprite.active)b.sprite.clearTint()});this.cameras.main.shake(65,.003);if(b.hp===0)this.finish(a)}}
finish(winner){if(this.ended)return;this.ended=true;const idx=this.fighters.indexOf(winner);if(idx>=0)this.rounds[idx]++;const over=this.rounds.some(n=>n>=2);this.banner=label(this,over?(idx===0?"KN VENCEU!":"NORMAN VENCEU!"):(idx===0?"KN VENCEU O ROUND":"NORMAN VENCEU O ROUND"),480,225,35);if(!over)this.time.delayedCall(3000,()=>{this.round++;this.reset()})}
update(_,delta){if(this.ended)return;const dt=Math.min(delta,50);this.timer-=dt/1000;const controls=[[this.keys.A,this.keys.D,this.keys.W,this.keys.S,this.keys.F,this.keys.G],[this.keys.LEFT,this.keys.RIGHT,this.keys.UP,this.keys.DOWN,this.keys.K,this.keys.L]];for(let i=0;i<2;i++){const f=this.fighters[i],enemy=this.fighters[1-i],c=controls[i];f.face=enemy.x>=f.x?1:-1;f.sprite.setFlipX(f.face<0);f.cool=Math.max(0,f.cool-dt);f.stun=Math.max(0,f.stun-dt);f.stamina=Math.min(100,f.stamina+dt*.016);if(f.stun===0){const distance=enemy.x-f.x;const dir=i===0?(c[1].isDown?1:0)-(c[0].isDown?1:0):Math.abs(distance)>86?Math.sign(distance):0;f.x=Phaser.Math.Clamp(f.x+dir*dt*.27,55,905);if(i===0&&c[2].isDown&&f.grounded){f.vy=-.76;f.grounded=false}if(i===0&&(Phaser.Input.Keyboard.JustDown(c[4])||Phaser.Input.Keyboard.JustDown(this.keys.K)))this.hit(f,enemy,"punch");if(i===0&&(Phaser.Input.Keyboard.JustDown(c[5])||Phaser.Input.Keyboard.JustDown(this.keys.L)))this.hit(f,enemy,"kick");f.sprite.setScale(1.13,i===0&&c[3].isDown&&f.grounded?.82:1.13)}f.vy+=dt*.0022;f.feet=Math.min(FLOOR,f.feet+f.vy*dt);if(f.feet>=FLOOR){f.feet=FLOOR;f.vy=0;f.grounded=true}f.sprite.setPosition(f.x,f.feet)}this.aiTimer-=dt;if(this.aiTimer<=0&&!this.ended){const enemy=this.fighters[1],player=this.fighters[0];if(Math.abs(enemy.x-player.x)<128&&enemy.stun<=0){this.hit(enemy,player,enemy.stamina>=19&&Math.random()<.4?"kick":"punch")}this.aiTimer=480+Math.random()*420}if(this.timer<=0){const [a,b]=this.fighters;this.finish(a.hp===b.hp?null:a.hp>b.hp?a:b)}this.renderHud()}
}
